[rule]
author = ["3292406328"]
description = "test"
from = "now-5m" # this is default value, change as needed
name = "Nmap Web Scanner Activity"

#risk_score = 21
severity = "low"

type = "query"
rule_id = "00000000-0000-0000-0000-000000000001"

query = '''
event.dataset : "zeek.http" and *Nmap*
'''


[[rule.threat]] # Example Tactic, Technique, Sub-Technique
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1046"
name = "Network Service Discovery"
reference = "https://attack.mitre.org/techniques/T1046/"


[rule.threat.tactic]
id = "TA0007"
name = "Discovery"
reference = "https://attack.mitre.org/tactics/TA0007/"

